namespace PatientMonitorDataLogger.PhilipsIntellivue.Models.Attributes;

public enum Language : ushort
{
    LANGUAGE_UNSPEC = 0,
    ENGLISH = 1,
    GERMAN = 2,
    FRENCH = 3,
    ITALIAN = 4,
    SPANISH = 5,
    DUTCH = 6,
    SWEDISH = 7,
    FINNISH = 8,
    NORWEG = 9,
    DANISH = 10,
    JAPANESE = 11,
    REP_OF_CHINA = 12,
    PEOPLE_REP_CHINA = 13,
    PORTUGUESE = 14,
    RUSSIAN = 15,
    BYELORUSSIAN = 16,
    UKRAINIAN = 17,
    CROATIAN = 18,
    SERBIAN = 19,
    MACEDONIAN = 20,
    BULGARIAN = 21,
    GREEK = 22,
    POLISH = 23,
    CZECH = 24,
    SLOVAK = 25,
    SLOVENIAN = 26,
    HUNGARIAN = 27,
    ROMANIAN = 28,
    TURKISH = 29,
    LATVIAN = 30,
    LITHUANIAN = 31,
    ESTONIAN = 32,
    KOREAN = 33,
}