namespace PatientMonitorDataLogger.PhilipsIntellivue.Models;

public enum ObjectClass : ushort
{
    NOM_MOC_VMO  = 1, //    VMO
    NOM_MOC_VMO_METRIC_NU  = 6, //    Numeric
    NOM_MOC_VMO_METRIC_SA_RT  = 9, //    Realtime Sample Array
    NOM_MOC_VMS_MDS  = 33, //    MDS
    NOM_MOC_VMS_MDS_COMPOS_SINGLE_BED  = 35, //    Composit Single Bed MDS
    NOM_MOC_VMS_MDS_SIMP  = 37, //    Simple MDS
    NOM_MOC_BATT  = 41, //    Battery
    NOM_MOC_PT_DEMOG  = 42, //    Patient Demographics
    NOM_MOC_VMO_AL_MON  = 54, //    Alert Monitor
    NOM_ACT_POLL_MDIB_DATA  = 3094, //    Poll Action
    NOM_NOTI_MDS_CREAT  = 3334, //    MDS Create
    NOM_NOTI_CONN_INDIC  = 3351, //    Connect Indication
    NOM_DEV_METER_CONC_SKIN_GAS  = 4264, //    Skin Gas
    NOM_DEV_METER_FLOW_BLD  = 4284, //    Blood Flow
    NOM_DEV_ANALY_CONC_GAS_MULTI_PARAM_MDS  = 4113, //    Gas Analyzer
    NOM_DEV_ANALY_CONC_GAS_MULTI_PARAM_VMD  = 4114, //    Gas
    NOM_DEV_METER_CONC_SKIN_GAS_MDS  = 4265, //    Skin Gas
    NOM_DEV_MON_PHYSIO_MULTI_PARAM_MDS  = 4429, //    Multi-Param
    NOM_DEV_PUMP_INFUS_MDS  = 4449, //    Pump Infus
    NOM_DEV_SYS_PT_VENT_MDS  = 4465, //    Ventilator
    NOM_DEV_SYS_PT_VENT_VMD  = 4466, //    Ventilator
    NOM_DEV_SYS_MULTI_MODAL_MDS  = 4493, //    Multi-Modal MDS
    NOM_DEV_SYS_MULTI_MODAL_VMD  = 4494, //    Multi-Modal
    NOM_DEV_SYS_VS_CONFIG_MDS  = 5209, //    config MDS
    NOM_DEV_SYS_VS_UNCONFIG_MDS  = 5213, //    unconfig MDS
    NOM_DEV_ANALY_SAT_O2_VMD  = 4106, //    sat O2
    NOM_DEV_ANALY_FLOW_AWAY_VMD  = 4130, //    Flow Away
    NOM_DEV_ANALY_CARD_OUTPUT_VMD  = 4134, //    C.O.
    NOM_DEV_ANALY_PRESS_BLD_VMD  = 4174, //    Press
    NOM_DEV_ANALY_RESP_RATE_VMD  = 4186, //    RR
    NOM_DEV_CALC_VMD  = 4206, //    Calculation
    NOM_DEV_ECG_VMD  = 4262, //    ECG
    NOM_DEV_METER_CONC_SKIN_GAS_VMD  = 4266, //    Skin Gas
    NOM_DEV_EEG_VMD  = 4274, //    EEG
    NOM_DEV_METER_TEMP_BLD_VMD  = 4350, //    Blood Temp
    NOM_DEV_METER_TEMP_VMD  = 4366, //    Temp
    NOM_DEV_MON_BLD_CHEM_MULTI_PARAM_VMD  = 4398, //    Bld Chem
    NOM_DEV_SYS_ANESTH_VMD  = 4506, //    Aneshesia
    NOM_DEV_GENERAL_VMD  = 5122, //    General
    NOM_DEV_ECG_RESP_VMD  = 5130, //    ECG-Resp
    NOM_DEV_ARRHY_VMD  = 5134, //    Arrythmia
    NOM_DEV_PULS_VMD  = 5138, //    Pulse
    NOM_DEV_ST_VMD  = 5142, //    ST
    NOM_DEV_CO2_VMD  = 5146, //    CO2
    NOM_DEV_PRESS_BLD_NONINV_VMD  = 5150, //    Noninv Press
    NOM_DEV_CEREB_PERF_VMD  = 5154, //    Cereb Perf
    NOM_DEV_CO2_CTS_VMD  = 5158, //    CO2 CTS
    NOM_DEV_CO2_TCUT_VMD  = 5162, //    TcCO2
    NOM_DEV_O2_VMD  = 5166, //    O2
    NOM_DEV_O2_CTS_VMD  = 5170, //    CTS
    NOM_DEV_O2_TCUT_VMD  = 5174, //    Tc02
    NOM_DEV_TEMP_DIFF_VMD  = 5178, //    Diff Temp
    NOM_DEV_CNTRL_VMD  = 5182, //    Control
    NOM_DEV_WEDGE_VMD  = 5190, //    Wedge
    NOM_DEV_O2_VEN_SAT_VMD  = 5194, //    O2 Vent Sat
    NOM_DEV_CARD_RATE_VMD  = 5202, //    HR
    NOM_DEV_METER_PRESS_VMD  = 5230, //    IUP
    NOM_DEV_PLETH_VMD  = 5238, //    Pleth
    NOM_SAT_O2_TONE_FREQ  = 61448, //    Private Attribute
    NOM_DEV_MON_FETAL_MULTI_PARAM_MDS  = 61833, //    Fetal Measurements
    NOM_DEV_ANALY_USOUND_VMD  = 61838, //    Fetal Ultrasound
    NOM_DEV_ECG_FETAL_VMD  = 61842, //    Fetal direct ECG
    NOM_DEV_ANALY_TOCO_VMD  = 61846, //    TOCO
    NOM_DEV_RECORDER_VMD  = 61862, //    Fetal Recorder
    NOM_DEV_STATISTICS_VMD  = 61870, //    OB statistics
    NOM_OBJ_BATT_SENSOR  = 62200, //    Wireless battery sensor
    NOM_DEV_ANALY_OB_TI  = 62244, //    Trace Interpretation
    NOM_DEV_ANALY_OB_TI_VMD  = 62246, //    Trace Interpretation
    NOM_DEV_ECG_MATERNAL_VMD  = 62310, //    MECG
    NOM_OBJ_BATT_SENSOR_CLSPO2  = 62523, //    Wireless SpO2 sensor
    NOM_OBJ_BATT_SENSOR_CLNBP  = 62524, //    Wireless NBP sensor
    NOM_OBJ_BATT_CHARGER_CLSPO2  = 62526, //    Wireless SpO2 charger
    NOM_OBJ_BATT_CHARGER_CLNBP  = 62527, //    Wireless NBP charger
    NOM_OBJ_XMTR_CLSPO2  = 62529, //    Wireless SpO2 Transducer
    NOM_OBJ_XMTR_CLNBP  = 62530, //    Wireless NBP Transducer
    NOM_OBJ_SETTINGS_CLSPO2  = 62532, //    Wireless SpO2 configuration
    NOM_OBJ_SETTINGS_CLNBP  = 62533, //    Wireless NBP configuration
    NOM_DEV_METER_TEMP_INFRARED  = 62556, //    Tympanic Temperature
    NOM_DEV_METER_TEMP_INFRARED_MDS  = 62557, //    Tympanic Temperature
    NOM_DEV_METER_TEMP_INFRARED_VMD  = 62558, //    Tympanic Temperature
    NOM_DEV_METER_TEMP_INFRARED_CHAN  = 62559, //    Tympanic Temperature
    NOM_OBJ_OBR_IF_1  = 63899, //    OBRadio Interface 1
    NOM_OBJ_OBR_CONFIG  = 63900, //    OB wireless configuration
    NOM_OBJ_OBR_CONFIG_MDS  = 63901, //    OB wireless configuration
    NOM_OBJ_OBR_CONFIG_VMD  = 63902, //    OB wireless configuration
    NOM_OBJ_OBR_CONFIG_CHAN  = 63903, //    OB wireless configuration
}